[build]
  # Command to build the app
  cmd = "go build -o main src/main.go"
  # Binary to watch
  bin = "main"
  # Working directory
  dir = "."
  # Patterns to watch
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Exclude files
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  # Command to run after build
  run_after_build = "chmod +x main"

[log]
  level = "debug"