version: "3.9"
services:
  backend:
    image: krikati-backend:latest
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SUPABASE_API_URL=${SUPABASE_API_URL}
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
    command: sh -c "echo 'ENV VARS:' && printenv && ./app"
    develop:
      watch:
        - path: .
          target: /app
          action: sync
