version: "3.9"
services:
  backend:
    image: krikati-backend:latest
    build: .
    ports:
      - "3000:3000"
    command: ["go", "run", "src/main.go"]
    develop:
      watch:
        - path: .
          target: /app
          action: sync
